name = "GrapheneQFT"
uuid = "b903362a-f3fb-4fd6-ad42-15d1112bb05b"
authors = ["alex <alerodin@gmail.com>"]
version = "0.1.0"

[deps]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"

[compat]
QuadGK = "2.4"
